# Generated by Django 2.0 on 2020-04-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputform',
            name='distance',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inputform',
            name='mobile',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
