# Generated by Django 2.0 on 2020-04-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintForm', '0002_auto_20200412_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputform',
            name='date',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
