# Generated by Django 2.0.6 on 2020-03-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputForm',
            fields=[
                ('complainant_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('father_husband_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mobile', models.BigIntegerField(blank=True, default=0, null=True)),
                ('address1', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('address2', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('distance', models.BigIntegerField(blank=True, default=0, null=True)),
                ('direction', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nature_offence', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('particulars_property', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('description_accused', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('witness_details', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('brief_facts', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
